# For production

version: "3.5"

services:
  db:
    container_name: "3d_db"
    image: postgres:14
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db

  backend:
    container_name: "3d_backend"
    build: ./backend
    restart: unless-stopped
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  frontend:
    container_name: "3d_frontend"
    restart: unless-stopped
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend

volumes:
  postgres_data: